# Generated by Django 5.0.2 on 2024-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
