# Generated by Django 5.0.2 on 2024-11-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
    ]
