# Generated by Django 5.0.2 on 2024-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='payment_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
