# Generated by Django 5.0.2 on 2024-11-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0002_task_task_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('payment_amount', models.PositiveIntegerField(default=0)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='task_documents/')),
                ('task_url', models.URLField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tasks', to='freelancers_app.customerprofile')),
            ],
        ),
    ]
