# Generated by Django 5.0.2 on 2024-11-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0003_alter_task_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='task_documents/'),
        ),
    ]
