# Generated by Django 5.0.2 on 2024-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0003_customer_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment_amount',
            field=models.CharField(blank=True, default='Amount not specified.', null=True),
        ),
    ]
