# Generated by Django 5.0.2 on 2024-11-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0008_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskapplication',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers_app.freelancerprofile'),
        ),
    ]
