# Generated by Django 5.0.2 on 2024-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0010_remove_customer_tasks_task_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
