# Generated by Django 5.0.2 on 2024-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0012_alter_task_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
