# Generated by Django 5.0.2 on 2024-11-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0013_customerprofile_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Tasks',
            new_name='Customer_Task',
        ),
    ]
