# Generated by Django 5.0.2 on 2024-11-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_app', '0014_rename_customer_tasks_customer_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_task',
            old_name='title',
            new_name='work_category',
        ),
    ]
